//
//  DesignSystem.swift
//  refomo
//
//  Design tokens for consistent UI across the app

import SwiftUI
import UIKit

// MARK: - Colors

extension Color {
    // pomodoroAccent is auto-generated from Asset Catalog (PomodoroAccent.colorset)
    // Access via: Color.pomodoroAccent (auto-generated by Xcode)

    // Semantic backgrounds
    static let cardBackground = Color(UIColor.secondarySystemBackground)
    static let inputBackground = Color(UIColor.tertiarySystemBackground)

    // Semantic text
    static let primaryText = Color(UIColor.label)
    static let secondaryText = Color(UIColor.secondaryLabel)
    static let tertiaryText = Color(UIColor.tertiaryLabel)
}

// MARK: - Spacing (8pt Grid)

enum Spacing {
    static let xs: CGFloat = 4    // Icon-text gap
    static let sm: CGFloat = 8    // Tight grouping
    static let md: CGFloat = 16   // Content padding
    static let lg: CGFloat = 20   // Screen edge margins
    static let xl: CGFloat = 24   // Section gaps
    static let xxl: CGFloat = 32  // Major sections
}

// MARK: - Corner Radius

enum CornerRadius {
    static let small: CGFloat = 8     // Small buttons
    static let medium: CGFloat = 10   // Input fields
    static let large: CGFloat = 12    // Cards
    static let sheet: CGFloat = 16    // Sheet top corners
    static func pill(height: CGFloat) -> CGFloat { height / 2 }
}

// MARK: - Shadows (HIG Compliant)

struct ShadowStyle {
    let color: Color
    let radius: CGFloat
    let x: CGFloat
    let y: CGFloat

    // Level 1: Subtle lift (drag handles)
    static let subtle = ShadowStyle(
        color: .black.opacity(0.08),
        radius: 4,
        x: 0,
        y: 1
    )

    // Level 2: Cards, modals
    static let card = ShadowStyle(
        color: .black.opacity(0.12),
        radius: 8,
        x: 0,
        y: 2
    )
}

extension View {
    func shadow(_ style: ShadowStyle) -> some View {
        self.shadow(color: style.color, radius: style.radius, x: style.x, y: style.y)
    }
}

// MARK: - Animation Helpers

struct AnimationConfig {
    // Check reduce motion preference
    static var reduceMotion: Bool {
        UIAccessibility.isReduceMotionEnabled
    }

    // Standard durations
    static let fast: Double = 0.15
    static let normal: Double = 0.3
    static let slow: Double = 0.5

    // Conditional animation
    static func animation(_ duration: Double = normal) -> Animation? {
        reduceMotion ? nil : .easeInOut(duration: duration)
    }
}

extension View {
    /// Applies animation only if Reduce Motion is not enabled
    func animateIfAllowed<V: Equatable>(_ value: V, duration: Double = AnimationConfig.fast) -> some View {
        self.animation(AnimationConfig.reduceMotion ? nil : .easeInOut(duration: duration), value: value)
    }

    /// Applies Liquid Glass effect on iOS 26+, falls back to accent color on earlier versions
    /// Note: glassEffect() will be available in iOS 26+
    @ViewBuilder
    func primaryButtonStyle(accent: Color = .pomodoroAccent) -> some View {
        // iOS 26+ will use: self.glassEffect(.regular.tint(accent))
        // Current fallback:
        self.background(accent)
    }
}
